### ISSUE TITLE
cont. error in collab

### ISSUE THREAD

**Issue by rexmirak** [hongfz16/EVA3D#11]
![image](https://user-images.githubusercontent.com/87246131/226061803-a4ce1c2e-6199-4423-8ea2-17f6ccda055a.png)
![image](https://user-images.githubusercontent.com/87246131/226061807-7f0b623d-7c3b-42ff-927c-c2369b69b99d.png)
![image](https://user-images.githubusercontent.com/87246131/226061810-4bddbae6-f0f4-4a18-ae9e-9b77d572b3a0.png)

**Comment by rexmirak** [comment]
![image](https://user-images.githubusercontent.com/87246131/226100670-bef4f094-f402-4aba-a1cc-a702f34d7622.png)
help resolving this error will be greatly appreciated

**Comment by zAuk000** [comment]
> ![image](https://user-images.githubusercontent.com/87246131/226100670-bef4f094-f402-4aba-a1cc-a702f34d7622.png) help resolving this error will be greatly appreciated

maybe you should train the model 300000 iteration first to get the pretrained model models_0300000.pt, or download the 0420000.pt from the readme.md file
