### ISSUE TITLE
Should I change the iter from 1,000,000 to 8,000,000 if I use single GPU to train?

### ISSUE THREAD

**Issue by LabEnbug** [hongfz16/EVA3D#16]
Hi,

Thank you very much for your outstanding work. While attempting to train, I noticed that regardless of the number of GPUs selected, the total time required remained constant. If I were to train using a single GPU, should I adjust the iteration count from 1,000,000 to 8,000,000 to account for the fact that you are training with 8 GPUs? Am I correct in understanding that the iteration count pertains to a single GPU?

Very thanks!

**Comment by hongfz16** [comment]
Hi. Thank you for your interest in our work.

In theory, yes, you need 8 times more iterations if you only use one GPU. But I am not sure whether you would get decent results since our batch size per GPU is quite small.
