### ISSUE TITLE
key error 

### ISSUE THREAD

**Issue by Kai-0515** [hongfz16/EVA3D#17]
hi I met the key error when use the smpl model in dataset.py(deepfashion block).
how can the smpl model to index the images name?
<img width="1302" alt="截屏2023-04-11 下午4 45 14" src="https://user-images.githubusercontent.com/57972031/231106190-78ec173d-6238-4273-9378-8c4516d85920.png">
<img width="890" alt="截屏2023-04-11 下午4 45 28" src="https://user-images.githubusercontent.com/57972031/231106239-c14e92d9-637e-4669-b87f-06e0d968f90d.png">

**Comment by hongfz16** [comment]
Hi, line 105 is meant to load a dict containing all the smpl annotations to the images. `SMPL_NEUTRAL.pkl` is SMPL model itself and should not be used here. If you are using DeepFashion, you may use the provided annotations `smpl.pkl`, which can be found in the download link we provide.
