### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by OvOtoQAQ** [hongfz16/EVA3D#18]
Thanks for your excellent work, fangzhou! Following your paper and other issues, I use 4 V100 and modify training iterations to 2,000,000, and change the batch parameter to 8 in your given train bash file as you mentioned in your paper. But it seems like more than    8000 hours needed to train the model rather than 10 days theoretically. Maybe I should set batch to 1 or just shut down before 1,000,000 iters? It kinda confuses me, please inform me how to adjust my settings.

All the best.

**Comment by OvOtoQAQ** [comment]
Sorry to bother, it seems I should just shut down when image quality is fine.

**Comment by hongfz16** [comment]
Hi. Sorry for the late reply. Thank you for your interest in our work and trying out the code.

Yes, you are right. Even though I set a large total iteration number. But usually I just stop training when the generation quality is satisfying.

**Comment by OvOtoQAQ** [comment]
Thanks for your reply :)
