### ISSUE TITLE
Custom images and texture

### ISSUE THREAD

**Issue by carlosedubarreto** [hongfz16/EVA3D#3]
Great project.
I was able to make it work here on my windows and I've got a doubt.
The way it is, is possible to create using custom images?

From what I saw on the code, seems like it can create (at the moment) using a demodataset that is a this pkl file
![image](https://user-images.githubusercontent.com/4061130/218253060-02592ab3-c288-481a-bad6-71cb6e5d5c49.png)

The idea is the release some code in the future for us to create our own "pkl" to use on EVA3D?

And is there an option to create the texture for the model?

Thanks a lot for the amazing code.

**Comment by hongfz16** [comment]
Hi. Thank you for trying out!

EVA3D is an unconditional 3D human generation model, which means the humans are just generated from random Gaussian noises. And the generated human can be controlled by SMPL parameters. Here in `sample_data.pkl`, we just provide a few samples for the controlling parameters like SMPL and camera.

We will release training codes in a few days, which can be used for custom images training.

Creating textures from NeRF for extracted meshes is not a very trivial thing to do. I actually implemented a very simple algorithm for this task in my other project [AvatarCLIP](https://github.com/hongfz16/AvatarCLIP/blob/e1bf57f4eee5c143ba07248356e6ad4aa99b2ba6/AvatarGen/AppearanceGen/main.py#L850). The idea is to render NeRF from multiple viewing angles and project rendered RGB to mesh vertices.

**Comment by carlosedubarreto** [comment]
What, this is nuts.
Didnt noticed that it was random. Its amazing.
I'll run it again to see the result. 

Didnt understand that it was a based on NeRF.

Wow. now I find it even more amazing. Thanks for the explanations.

**Comment by hongfz16** [comment]
You are welcome. Feel free to reopen the issue if you have any further questions!
