### ISSUE TITLE
ERROR: [Errno Incorrect file size] checkpoint/512x256_deepfashion/volume_renderer/models_0420000.pt

### ISSUE THREAD

**Issue by Stradichenko** [hongfz16/EVA3D#4]
Following error when running:
`python download_models.py`
```bash
Downloading EVA3D model pretrained on DeepFashion.
  0%|                                                               | 2.26k/160M [00:00<5:22:05, 8.30kB/s][Errno Incorrect file size] checkpoint/512x256_deepfashion/volume_renderer/models_0420000.pt
```

**Comment by carlosedubarreto** [comment]
I also had that error, but it automaticaly downloed another file and it worked on my pc.

**Comment by hongfz16** [comment]
Hi @Stradichenko, thank you for trying out. Downloading files from Google Drive using scripts has high chances to fail. So the script would repeatedly try downloading until success. The error message is just one failed trial and can be ignored. In case the script fails, you might also download manually using the link in the script.

Also thank @carlosedubarreto for your clarification!

I'm closing the issue. Feel free to reopen it if you have further questions.
