### ISSUE TITLE
smpl_template_sdf

### ISSUE THREAD

**Issue by XinyaChen21** [hongfz16/EVA3D#5]
Thanks for the great work!
How do you generate the smpl_template_sdf？Is the smpl_template_sdf in part local space and all the part share a same smpl_template_sdf? Could you release the code for generating smpl_template_sdf?

**Comment by hongfz16** [comment]
Hi, we simply transfer mean shape SMPL mesh to SDF to get smpl_template_sdf. The tool we used can be found [here](https://github.com/marian42/mesh_to_sdf).

Closing the issue. Feel free to reopen if you have further questions.

**Comment by XinyaChen21** [comment]
The code uses the XYZ in part local space to query the smpl_template_sdf. Is the smpl_template_sdf in part local space and do all the parts share the same smpl_template_sdf?

**Comment by XinyaChen21** [comment]
The code uses the XYZ in part local space to query the smpl_template_sdf. Is the smpl_template_sdf in part local space and do all the parts share the same smpl_template_sdf?

**Comment by hongfz16** [comment]
The smpl_template_sdf is in the SMPL local space not part local space, which means all the queries will be first transferred to SMPL local space.
Yes, all the parts share the same smpl_template_sdf.

**Comment by XinyaChen21** [comment]
Thanks for replying.
But Smpl_v_inv seems to transform the points in observation space to part local space instead of T pose canonical space. What does rel_transforms generated by batch_rigid_transform() mean?

**Comment by hongfz16** [comment]
`smpl_v_inv` transform points in the observation space to canonical space.

The transformation from canonical space to part local space happens in line 1032 `eva3d_deepfashion.py`
