### ISSUE TITLE
RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented

### ISSUE THREAD

**Issue by soubhiksanyal** [hongfz16/EVA3D#7]
Hi,

Thank you for releasing the great codebase. I am having some issues while running the deepfashion training code. I am keep getting the error "RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented". My pytorch version is 1.11.0 and cuda version is 11.3. Can you please help regarding this?

**Comment by hongfz16** [comment]
Hi,
You might downgrade your pytorch version for a fast solution. Or you may dig into the codes to see which operator is not supported by your pytorch version.

**Comment by soubhiksanyal** [comment]
Finally, I can run it for the latest torch  1.13.1 with CUDA 11.7. The main problem was inherited from the custom operations implemented by the older stylegan3 codebase. And EVA3D was built on top of stylegan3, stylegan-ada or EG3D, I suppose.  When pytorch upgraded their version this particular part was not backward compatible

Please check these related issues if you want to fix them (hint: stylegan3 already updated their torch_utils functions, so one can directly use them here for the latest versions)

https://github.com/pytorch/pytorch/issues/75018
https://github.com/NVlabs/stylegan3/issues/145

**Comment by hongfz16** [comment]
Cool! Thank you for the helpful advice.
Yes. EVA3D is built on top of StyleSDF and PI-GAN, which possibly borrow some codes from StyleGAN.
I might fix it sometime in the future. Closing the issue.

**Comment by zhan-xu** [comment]
**Edit**: I modified grid_sample_gradfix.py in torch_utils/ops and it seems working now
```
diff --git a/torch_utils/ops/grid_sample_gradfix.py b/torch_utils/ops/grid_sample_gradfix.py
index 4e96cef..3446e7d 100755
--- a/torch_utils/ops/grid_sample_gradfix.py
+++ b/torch_utils/ops/grid_sample_gradfix.py
@@ -13,6 +13,7 @@ Only works on 2D images and assumes
 
 import warnings
 import torch
+from pkg_resources import parse_version
 
 # pylint: disable=redefined-builtin
 # pylint: disable=arguments-differ
@@ -21,6 +22,8 @@ import torch
 #----------------------------------------------------------------------------
 
 enabled = True  # Enable the custom op by setting this to true.
+_use_pytorch_1_11_api = parse_version(torch.__version__) >= parse_version('1.11.0a') # Allow prerelease builds of 1.11
+_use_pytorch_1_12_api = parse_version(torch.__version__) >= parse_version('1.12.0a') # Allow prerelease builds of 1.12
 
 #----------------------------------------------------------------------------
 
@@ -32,12 +35,7 @@ def grid_sample(input, grid):
 #----------------------------------------------------------------------------
 
 def _should_use_custom_op():
-    if not enabled:
-        return False
-    if any(torch.__version__.startswith(x) for x in ['1.7.', '1.8.', '1.9']):
-        return True
-    warnings.warn(f'grid_sample_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.grid_sample().')
-    return False
+    return enabled
 
 #----------------------------------------------------------------------------
 
@@ -62,7 +60,13 @@ class _GridSample2dBackward(torch.autograd.Function):
     @staticmethod
     def forward(ctx, grad_output, input, grid):
         op = torch._C._jit_get_operation('aten::grid_sampler_2d_backward')
-        grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
+        if _use_pytorch_1_12_api:
+            op = op[0]
+        if _use_pytorch_1_11_api:
+            output_mask = (ctx.needs_input_grad[1], ctx.needs_input_grad[2])
+            grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False, output_mask)
+        else:
+            grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
         ctx.save_for_backward(grid)
         return grad_input, grad_grid
```

Thank you for the hint.

**Original post:**
HI @soubhiksanyal I replaced the torch_utils folder with the latest torch_utils folder from stylegan3 but still get the same error. How did you solve it? Thank you.
