### ISSUE TITLE
Is it possible to train the model on an NVIDIA 2080ti or 3090?

### ISSUE THREAD

**Issue by liwenssss** [hongfz16/EVA3D#8]
Hi, thanks for your nice work. I notice that you mentioned in the parper you train the model on NVIDIA V100. I want to know that Is it possible to train the model on an NVIDIA 2080ti or 3090?
best wishes

**Comment by hongfz16** [comment]
Thank you for your interest in our work. The full size model might not be able to fit in NVIDIA 2080ti or 3090. A few modifications might get things to work.

1. Reduce the rendering size from 512x256 to 256x128. An additional 2D super-resolution module might be able to fill in the resolution gap (just like what StyleSDF and EG3D do).
2. Reduce MLP layers or channel dimensions to make the network smaller.
3. Reduce the batch size.

However, even if you successfully get the model to train on smaller GPU memories. There is no guarantee that you can reproduce our results. GAN training is sensitive to batch size. And too shallow MLPs might not have enough capacity to model the complex human body.

**Comment by hongfz16** [comment]
Closing. Feel free to reopen it if you have further questions.
